name: Update README Stats

on:
  schedule:
    - cron: "0 0 1 * *"  # 每月1号的00:00 UTC执行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Generate Stats
        run: |
          mkdir -p imgs
          curl "https://lencx-stats.vercel.app/api?username=${{ github.repository_owner }}&locale=en&theme=default" -o imgs/stats-en-light.svg
          curl "https://lencx-stats.vercel.app/api?username=${{ github.repository_owner }}&locale=en&theme=dark"  -o imgs/stats-en-dark.svg
          curl "https://lencx-stats.vercel.app/api?username=${{ github.repository_owner }}&locale=cn&theme=default" -o imgs/stats-cn-light.svg
          curl "https://lencx-stats.vercel.app/api?username=${{ github.repository_owner }}&locale=cn&theme=dark"  -o imgs/stats-cn-dark.svg

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add imgs/*.svg || true
          # 如果有变更则提交并推送，否则跳过
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update stats (multi-language & theme)"
            git push
          else
            echo "No changes to commit"
          fi
